GET http://localhost:3000/getUsers

###

GET http://localhost:3000/getUser/1

###

POST http://localhost:3000/createUser
Content-Type: application/json

{
    "name": "eric",
    "email": "e@p.fr"
}

###

DELETE http://localhost:3000/deleteUsers

###

DELETE http://localhost:3000/deleteUser/3